### ISSUE TITLE
[Bug]: Error On UiManagerInit

### ISSUE THREAD

**Issue by genericname02** [RequiDev/ReMod.Core#11]
"void ReMod.Core.Managers.UiManager..ctor(string,UnityEngine.Sprite)"

Debug Steps: 
Ive tried to null the sprite so it wouldn't use one but i still get the same error my sprite is in the location that I give it, Ive tried resource manager and my own way of loading from disk. I genuinely have no idea why this is happening Ive upgraded to the newest version and still getting this same error Thank you in advanced.

**Comment by RequiDev** [comment]
I'll need more information to tell you what's wrong.
