### ISSUE TITLE
[Feature]: Print Core version to console/logs

### ISSUE THREAD

**Issue by rakosi2** [RequiDev/ReMod.Core#22]
**Is your feature request related to a problem? Please describe.**
Currently, it is a pain to detect if core is outdated. I have to look at main mod's error message which can change between main mods and also core version.

**Describe the solution you'd like**
I would like the ReMod.Core version number to be printed somewhere in the logs.

**Describe alternatives you've considered**
I am currently detecting Main Mod's error message for outdated core but it is a pain to upkeep.

**Additional context**
Mainly needed for Lum MelonLoader Log Scanner.

**Comment by ddakebono** [comment]
Was gonna shove that in last night, but the action needs to be updated to set the DLL version to the GitHub action build id thing

**Comment by RequiDev** [comment]
RegisterSafe is not guaranteed to fire.
