### ISSUE TITLE
[Bug]: `ReRadioTogglePage` not showing on second time

### ISSUE THREAD

**Issue by Tolfx** [RequiDev/ReMod.Core#26]
So I have a `ReRadioTogglePage` with items, and when I access the page I got all my toggles nothing weird. But when I exit and come up, all of the toggles are gone.

The issue is `_isUpdated`, idk what purpose it has but when I use `Open` it sets to `false` and then we can never open it again. So either I'm using this class wrong.

For the moment I will just remove it on my builds as a proper fix.

**Comment by ddakebono** [comment]
Radio toggles were changed inside VRChat, gonna be looking at them tonight and try to figure out what exactly went dumb. The audio device selection menu doesn't have the same behavior of clearing all entries on enable, so I'd like to figure out why it's broken now.

**Comment by ddakebono** [comment]
Ideally _isUpdated will only rebuild the menu if there is changes needed, which was functional on the original implementation, until the 1205 nation attacked.

**Comment by Tolfx** [comment]
I see, well thanks for the quick response!

**Comment by PennyBunny** [comment]
Bono good boy, thank you for looking at it!

**Comment by ddakebono** [comment]
OK! After an entire day of fiddle farting with it I have a solution, I've ended up basically redoing 90% of the implementation and stripping out all of VRChat's DataModel crap. Pretty much just hijacked the base UI parts and redid the logic behind it, StyleElements are still doing their job so everything has animations and works good. No more dealing with the absolute hell that they implemented on it.

I'll be cleaning up and finishing hooking everything up tomorrow hopefully, tho it might end up being Thursday if I run out of time before my movie night.

**Comment by PennyBunny** [comment]
*pat pat* plz not morbius

**Comment by Myrkie** [comment]
That text make you sound broken my dude.

**Comment by ddakebono** [comment]
Rework of ReRadioTogglePage has been pushed out, some changes in how it works but should be far more reliable as it doesn't use any of the original VRChat components, just stock Unity UI components now.

**Comment by Myrkie** [comment]
less vrchat stuff = more reliability
